- hosts: all
  vars:
      ad_domain: appcara.net
      ad_domain_netbios: appcara.net
      ad_ou: Computers
      ad_password: Qwe123!
      ad_user: drake.admin
  roles:
     - role: mrlesmithjr.domain-join
